# Generated by Django 4.2.7 on 2023-11-10 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('desired_degree', models.TextField(null=True)),
                ('required_degree', models.TextField(null=True)),
                ('role', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='applicants',
            field=models.ManyToManyField(through='api.ApplicantLanguage', to='api.applicant'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_at', models.DateField()),
                ('left_at', models.DateField(null=True)),
                ('hired_reason', models.TextField(null=True)),
                ('left_reason', models.TextField(null=True)),
                ('role', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_proficiency', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('required_proficiency', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_proficiency', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('required_proficiency', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.language')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificate')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_at', models.DateField()),
                ('left_at', models.DateField(null=True)),
                ('hired_reason', models.TextField(null=True)),
                ('left_reason', models.TextField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='applications',
            field=models.ManyToManyField(through='api.VacancyApplication', to='api.applicant'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='certificates',
            field=models.ManyToManyField(through='api.VacancyCertificate', to='api.certificate'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='languages',
            field=models.ManyToManyField(through='api.VacancyLanguage', to='api.language'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(through='api.VacancySkill', to='api.skill'),
        ),
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('graduated_at', models.DateField(null=True)),
                ('degree', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.educationalinstitute')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateField(null=True)),
                ('expired_at', models.DateField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='certificates',
            field=models.ManyToManyField(through='api.ApplicantCertificate', to='api.certificate'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.ManyToManyField(through='api.ApplicantEducation', to='api.educationalinstitute'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='external_experience',
            field=models.ManyToManyField(through='api.WorkExperience', to='api.company'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(through='api.ApplicantSkill', to='api.skill'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='applicants',
            field=models.ManyToManyField(through='api.ApplicantCertificate', to='api.applicant'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vacancies',
            field=models.ManyToManyField(through='api.VacancyCertificate', to='api.vacancy'),
        ),
        migrations.AddField(
            model_name='company',
            name='ex_employees',
            field=models.ManyToManyField(through='api.WorkExperience', to='api.applicant'),
        ),
        migrations.AddField(
            model_name='language',
            name='vacancies',
            field=models.ManyToManyField(through='api.VacancyLanguage', to='api.vacancy'),
        ),
        migrations.AddField(
            model_name='skill',
            name='applicants',
            field=models.ManyToManyField(through='api.ApplicantSkill', to='api.applicant'),
        ),
        migrations.AddField(
            model_name='skill',
            name='vacancies',
            field=models.ManyToManyField(through='api.VacancySkill', to='api.vacancy'),
        ),
    ]
