# Generated by Django 4.2.7 on 2023-11-17 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_applicant_vacancies_alter_certificate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteducation',
            name='graduated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='hired_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='left_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancyapplication',
            name='left_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancylanguage',
            name='desired_proficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vacancylanguage',
            name='required_proficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vacancyskill',
            name='desired_proficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vacancyskill',
            name='required_proficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='hired_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='left_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='left_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
